version: "3.8"
services:
  redis:
    image: "redis:alpine"
    container_name: chatbot-redis
    ports:
      - "6379:6379"
    volumes:
      - chatbot_redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  qdrant:
    image: "qdrant/qdrant"
    container_name: chatbot-qdrant-vector-db
    ports:
      - 6333:6333 # tcp
      - 6334:6334 # grpc

    volumes:
      - chatbot_qdrant_data:/qdrant/storage # Persist data in the Docker volume
    restart: always

  backend:
    build:
      context: ./chatbot_backend
      dockerfile: Dockerfile
    container_name: newschatbot-fastapi-backend
    restart: always
    volumes:
      - ./chatbot_backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - qdrant
    env_file:
      - chatbot_backend/.env

  frontend:
    build:
      context: ./chatbot_frontend
      dockerfile: Dockerfile
    container_name: investment-react-frontend
    restart: always
    volumes:
      - ./chatbot_frontend:/app
      - /app/node_modules
    ports:
      - 5173:5173
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  chatbot_redis_data:
  chatbot_qdrant_data:
